package Baton::Model::Baton;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Baton::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:baton',
        user => 'root',
        password => '',
    }
);

=head1 NAME

Baton::Model::Baton - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Baton>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Baton::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

中森 創太

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
